name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self add poetry-plugin-export
          make zip
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat build/script.elementum.jackett/addon.xml
          gh release create "${{github.ref_name}}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{github.ref_name}}" \
              --generate-notes \
              build/script.elementum.jackett-*.zip
